/**
*   Use this command in order to remove prefix for each user
**/
SELECT * FROM V$PARAMETER WHERE NAME = 'COMMON_USER_PREFIX';

CREATE USER "C##CORALLO" IDENTIFIED BY "password" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
GRANT ALL PRIVILEGES TO C##CORALLO;

