
-- Data Warehouse Profile
CREATE USER "LOGISTICS"
    PROFILE "DEFAULT"
    IDENTIFIED BY "password"
    DEFAULT TABLESPACE "USERS"
    TEMPORARY TABLESPACE "TEMP"
    QUOTA UNLIMITED ON USERS
    ACCOUNT UNLOCK;


GRANT "CONNECT" TO "LOGISTICS";

GRANT CREATE ANY TABLE TO "LOGISTICS";
GRANT ALTER ANY TABLE TO "LOGISTICS";
GRANT DROP ANY TABLE TO "LOGISTICS";
