# Types definition

# Company and Operationals drop
DROP TABLE COMPANY;
DROP TABLE OPERATIONAL_CENTER;
DROP TYPE COMPANY_TY FORCE;
DROP TYPE SERVICE_TY FORCE;
DROP TYPE SERVICES_TY FORCE;

DROP TABLE OPERATIONAL_CENTERS;

DROP TYPE OPERATIONAL_CENTER_TY FORCE;
DROP TYPE OPERATIONAL_CENTERS_TY FORCE;

# Team Drop
DROP TABLE TEAM;
DROP TYPE TEAM_TY FORCE;
DROP TYPE MEMBER_TY FORCE;
DROP TYPE MEMBERS_TY FORCE;

# Customer Drop
DROP TABLE CUSTOMER;

DROP TYPE CUSTOMER_TY FORCE;

DROP TYPE BUSINESS_TY FORCE;

DROP TYPE INDIVIDUAL_TY FORCE;

DROP TYPE PERSON_TY FORCE;

DROP TYPE ACCOUNT_TY FORCE;

DROP TYPE ACCOUNTS_TY FORCE;

DROP TYPE ADDRESS_TY FORCE;


# Order Drop

DROP TABLE OPERATION_ORDER;
DROP TABLE HISTORICAL_ORDER;

DROP TYPE ORDER_TY FORCE;

DROP TYPE HISTORICAL_ORDER_TY FORCE;

DROP TYPE DELIVERY_TY FORCE;

DROP TYPE PLACEMENT_TY FORCE;

# Company and Operationals creation

CREATE OR REPLACE TYPE SERVICE_TY AS OBJECT (
    code INTEGER,
    name VARCHAR2(50),
    description VARCHAR2(200)
);
CREATE OR REPLACE TYPE SERVICES_TY AS TABLE OF SERVICE_TY;
CREATE OR REPLACE TYPE COMPANY_TY AS OBJECT (
    name VARCHAR(30),
    services SERVICES_TY
);

CREATE TABLE COMPANY OF COMPANY_TY (
  CONSTRAINT COMPANY_PK PRIMARY KEY (name) ENABLE 
)
NESTED TABLE services STORE as services_TAB;

CREATE OR REPLACE TYPE ADDRESS_TY AS OBJECT (
    street VARCHAR2(50),
    city VARCHAR2(10),
    province VARCHAR2(5),
    zipcode VARCHAR2(5)
);
CREATE OR REPLACE TYPE OPERATIONAL_CENTER_TY AS OBJECT (
    code INTEGER,
    name VARCHAR2(20),
    address ADDRESS_TY,
    company REF COMPANY_TY
);

CREATE TABLE OPERATIONAL_CENTER OF OPERATIONAL_CENTER_TY (
    SCOPE FOR (company) IS COMPANY,
    CONSTRAINT OPERATIONAL_CENTER_PK PRIMARY KEY (code) ENABLE 
);


# Team Creation
CREATE OR REPLACE TYPE PERSON_TY AS OBJECT (
    name VARCHAR2(20),
    surname VARCHAR2(20)
)
NOT INSTANTIABLE
NOT FINAL;
CREATE OR REPLACE TYPE MEMBER_TY UNDER PERSON_TY (
    CF CHAR(16)
);
CREATE OR REPLACE TYPE MEMBERS_TY AS VARRAY(8) OF MEMBER_TY;

CREATE OR REPLACE TYPE TEAM_TY AS OBJECT (
    code INTEGER,
    name VARCHAR2(20),
    noOperations INTEGER,
    score INTEGER,
    members MEMBERS_TY,
    operationalCenterRef REF OPERATIONAL_CENTER_TY
);
CREATE TABLE TEAM OF TEAM_TY (
  SCOPE FOR (operationalCenterRef) IS OPERATIONAL_CENTER,
  CONSTRAINT TEAM_PK PRIMARY KEY (code) ENABLE
);

# Customer Creation

CREATE OR REPLACE TYPE ACCOUNT_TY AS OBJECT (
    code INTEGER
);
CREATE OR REPLACE TYPE ACCOUNTS_TY AS TABLE OF ACCOUNT_TY;

CREATE OR REPLACE TYPE CUSTOMER_TY UNDER PERSON_TY (
    code INTEGER,
    email VARCHAR2(50),
    accounts ACCOUNTS_TY,
    type VARCHAR2(20)
)
NOT FINAL;

CREATE OR REPLACE TYPE BUSINESS_TY UNDER CUSTOMER_TY();
CREATE OR REPLACE TYPE INDIVIDUAL_TY UNDER CUSTOMER_TY();

CREATE TABLE CUSTOMER OF CUSTOMER_TY (
  CONSTRAINT CUSTOMER_PK PRIMARY KEY (code) ENABLE 
)
NESTED TABLE accounts STORE as accounts_TAB;


# Order Creation

CREATE OR REPLACE TYPE DELIVERY_TY AS OBJECT (
    customerFeedback VARCHAR2(200),
    deliveryTime INTERVAL DAY TO SECOND
);
# INSERT INTO ..... (..., INTERVAL '5 12:30:45' DAY TO SECOND);

CREATE OR REPLACE TYPE PLACEMENT_TY AS OBJECT (
    placementBy VARCHAR2(100)
);

CREATE OR REPLACE TYPE ORDER_TY AS OBJECT (
    code INTEGER,
    type VARCHAR2(10),
    creation_date DATE,
    cost NUMBER(15, 2),
    teamRef REF TEAM_TY,
    accountRef REF ACCOUNT_TY,
    placement PLACEMENT_TY,
    delivery DELIVERY_TY
)
NOT FINAL;

CREATE OR REPLACE TYPE HISTORICAL_ORDER_TY UNDER ORDER_TY();

CREATE TABLE OPERATION_ORDER OF ORDER_TY (
    SCOPE FOR (teamRef) IS TEAM,
    CONSTRAINT OPERATION_ORDER_PK PRIMARY KEY (code) ENABLE 
);
CREATE TABLE HISTORICAL_ORDER OF HISTORICAL_ORDER_TY(
    SCOPE FOR (teamRef) IS TEAM,    
    CONSTRAINT HISTORICAL_OPERATION_ORDER_PK PRIMARY KEY (code) ENABLE 
);
