# With system USER:

SELECT * FROM V$PARAMETER WHERE NAME = 'common_user_prefix';

ALTER SYSTEM SET common_user_prefix = '' SCOPE = SPFILE;
/**
 SCOPE SPFILE because common_user_prefix is static (ISSYS_MODIFIABLE = FALSE). This updates the SPFILE but doesn't apply the change until the database is restarted.
# RESTART DATABASE
**/

CREATE USER "LOGISTICS"
    PROFILE "DEFAULT"
    IDENTIFIED BY "password"
    DEFAULT TABLESPACE "USERS"
    TEMPORARY TABLESPACE "TEMP"
    QUOTA UNLIMITED ON USERS
    ACCOUNT UNLOCK;

GRANT "CONNECT" TO "LOGISTICS";

GRANT CREATE ANY TABLE TO "LOGISTICS";
GRANT ALTER ANY TABLE TO "LOGISTICS";
GRANT DROP ANY TABLE TO "LOGISTICS";

GRANT CREATE ANY TYPE TO "LOGISTICS";
GRANT ALTER ANY TYPE TO "LOGISTICS";
GRANT DROP ANY TYPE TO "LOGISTICS";

GRANT CREATE ANY PROCEDURE TO "LOGISTICS";
GRANT ALTER ANY PROCEDURE TO "LOGISTICS";
GRANT DROP ANY PROCEDURE TO "LOGISTICS";

GRANT CREATE ANY TRIGGER TO "LOGISTICS";
GRANT ALTER ANY TRIGGER TO "LOGISTICS";
GRANT DROP ANY TRIGGER TO "LOGISTICS";