# Types definition
CREATE OR REPLACE TYPE ADDRESS_TY AS OBJECT (
    street VARCHAR2(50),
    city VARCHAR2(10),
    province VARCHAR2(5)    
);

CREATE OR REPLACE TYPE SERVICE_TY AS OBJECT (
    code INTEGER,
    name VARCHAR2(20),
    description VARCHAR2(200)
);
CREATE OR REPLACE TYPE SERVICES_TY AS TABLE OF SERVICE_TY;

CREATE OR REPLACE TYPE OPERATIONAL_CENTER_TY AS OBJECT (
    code INTEGER,
    name VARCHAR2(20),
    region VARCHAR2(20),
    address ADDRESS_TY
);
CREATE OR REPLACE TYPE OPERATIONAL_CENTERS_TY AS TABLE OF OPERATIONAL_CENTER_TY;

CREATE OR REPLACE TYPE COMPANY_TY AS OBJECT (
    name VARCHAR(30),
    services SERVICES_TY,
    operationalCenters OPERATIONAL_CENTERS_TY 
);

CREATE OR REPLACE TYPE DELIVERY_TY AS OBJECT (
    customerFeedback VARCHAR2(200),
    deliveryTime INTERVAL DAY TO SECOND
);
# INSERT INTO ..... (..., INTERVAL '5 12:30:45' DAY TO SECOND);

CREATE OR REPLACE TYPE PLACEMENT_TY AS OBJECT (
    placementBy VARCHAR2(100)
);


CREATE OR REPLACE TYPE ACCOUNT_TY AS OBJECT (
    code INTEGER
);

CREATE OR REPLACE TYPE PERSON_TY AS OBJECT (
    name VARCHAR2(20),
    surname VARCHAR2(20)
)
NOT INSTANTIABLE
NOT FINAL;


CREATE OR REPLACE TYPE CUSTOMER_TY UNDER PERSON_TY (
    code INTEGER,
    email VARCHAR2(50)
)
NOT FINAL;

CREATE OR REPLACE TYPE BUSINESS_TY UNDER CUSTOMER_TY();
CREATE OR REPLACE TYPE INDIVIDUAL_TY UNDER CUSTOMER_TY();

CREATE OR REPLACE TYPE MEMBER_TY UNDER PERSON_TY (
    CF CHAR(16)
);

CREATE OR REPLACE TYPE MEMBERS_TY AS VARRAY(8) OF MEMBER_TY;

CREATE OR REPLACE TYPE TEAM_TY AS OBJECT (
    code INTEGER,
    name VARCHAR2(20),
    noOperations INTEGER,
    score INTEGER,
    members MEMBER_TY
);

CREATE OR REPLACE TYPE ORDER_TY AS OBJECT (
    code INTEGER,
    type VARCHAR2(10),
    date DATE,
    cost NUMBER(15, 2),
    teamRef REF(TEAM_TY),
    accountRef REF(ACCOUNT_TY),
    placement PLACEMENT_TY,
    delivery DELIVERY_TY
);